server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/java8PersonelYonetim"
    username: "postgres"
    password: "23061995"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update # create-> her seferinden yeniden oluştur. create-drop-> uygulama kapatıldığında tabloları siler. update-> varsa günceller yoksa oluşturur.
    show-sql: true